### ISSUE TITLE
`An error occurred: module 'importlib.metadata' has no attribute 'packages_distributions'`

### ISSUE THREAD

**Issue by ReubenFrankel** [googleapis/python-api-core#857]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-api-core/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Ubuntu 22.04.5 LTS
  - Python version: Python 3.9.21
  - pip version: 24.3.1
  - `google-api-core` version: 2.28.1

#### Steps to reproduce

  1. Import `google.api_core` in Python REPL
  2. Observed error printed to stdout

#### Code example

```console
$ .meltano/extractors/tap-bigquery/venv/bin/python
Python 3.9.21 (main, Dec  3 2024, 17:50:13) 
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Ctrl click to launch VS Code Native REPL
>>> import google.api_core
An error occurred: module 'importlib.metadata' has no attribute 'packages_distributions'
/home/reuben/meltano/bigquery-test/.meltano/extractors/tap-bigquery/venv/lib/python3.9/site-packages/google/api_core/_python_version_support.py:252: FutureWarning: You are using a Python version (3.9.21) past its end of life. Google will update google.api_core with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.api_core.
  warnings.warn(message, FutureWarning)
>>>
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

---

This is happening because `importlib.metadata.packages_distributions` was added in Python 3.10, but the current version check implementation allows this to be called for 3.8 and above: https://github.com/googleapis/python-api-core/blob/c97b3a004044ebf8b35c2a7ba97409d7795e11b0/google/api_core/_python_version_support.py#L150-L176

In our case, this generally wouldn't be a problem if the error was logged to stderr rather than printed, as we use following a specification that is particularly sensitive to stdout pollution.

**Comment by eecsmap** [comment]
Observed same issue on Windows python 3.9 with api-core 2.28.x

Error introduced in https://github.com/googleapis/python-api-core/pull/832

At _python_version_support.py line 165

```python
    from importlib import metadata

    def _get_pypi_package_name(module_name):
        """Determine the PyPI package name for a given module name."""
        try:
            # Get the mapping of modules to distributions
            module_to_distributions = metadata.packages_distributions()
```

packages_distributions does not exist in importlib.metadata in python 3.9.
